import { EmbedBuilder } from "discord.js";

const tips = [
  "Use the Pomodoro Technique: 25 minutes of focus, followed by a 5-minute break",
  "Create mind maps to connect different concepts",
  "Teach what you learn to someone else to reinforce your understanding",
	"Use flashcards to memorize key information",
	"Take regular breaks to avoid burnout",
	"Stay hydrated and eat healthy snacks to maintain your energy levels",
	"Get enough sleep to improve memory retention",
	"Exercise regularly to boost your brainpower",
	"Use mnemonic devices to remember complex information",
	"Set specific, achievable goals to stay motivated",
	"Join a study group to share knowledge and resources",
	"Use online tools like Anki, Quizlet, or WeStu to organize your study materials",
	"Review your notes regularly to reinforce your learning",
	"Practice active recall by testing yourself on the material",
	"Stay positive and believe in your ability to succeed",
	"Reward yourself for reaching study milestones",
	"Create a study schedule and stick to it",
	"Find a quiet, comfortable study space to minimize distractions",
	"Listen to instrumental music or white noise to help you focus",
	"Use the Feynman Technique to simplify complex topics",
	"Take practice tests to assess your understanding",
	"Use the Cornell note-taking system to organize your notes",
	"Break down large tasks into smaller, manageable chunks",
	"Use the 80/20 rule to focus on the most important topics",
	"Stay curious and ask questions to deepen your understanding",
	"Use spaced repetition to review information at optimal intervals",
	"Visualize your goals and the benefits of achieving them",
	"Stay consistent and make studying a daily habit",
	"Seek help from teachers, tutors, or online resources when needed",
	"Stay organized and keep track of your progress",
	"Stay positive and persevere through challenges",
	"Take care of your mental health and well-being",
	"Stay curious and explore new topics outside your comfort zone",
	"Use technology to enhance your learning experience",
	"Stay motivated by setting rewards for completing tasks",
	"Practice mindfulness and relaxation techniques to reduce stress",
	"Stay focused on your long-term goals and aspirations",
	"Use positive affirmations to boost your confidence",
	"Stay disciplined and avoid procrastination",
	"Reflect on your learning and identify areas for improvement",
	"Stay humble and open to feedback from others",
	"Stay patient and trust the learning process",
	"Stay resilient and bounce back from setbacks",
	"Stay adaptable and embrace change",
	"Stay grateful and appreciate the opportunities to learn",
	"Stay inspired by the success stories of others",
	"Stay connected with a supportive community of learners",
	"Stay creative and find innovative ways to study",
	"Stay balanced and prioritize your well-being",
	"Stay humble and acknowledge your strengths and weaknesses",
	"Stay focused and avoid multitasking",
	"Stay curious and explore new ideas and perspectives",
	"Stay committed and follow through on your goals",
	"Stay positive and maintain a growth mindset",
	"Stay motivated and celebrate your progress",
	"Stay resilient and bounce back from setbacks",
	"Stay disciplined and manage your time effectively",
	"Stay organized and keep track of your tasks",
	"Stay focused and avoid distractions",
	"Stay consistent and make studying a habit",
	"Stay curious and ask questions",
	"Stay engaged and participate actively in your learning",
	"Stay open-minded and consider different viewpoints",
	"Stay patient and persevere through challenges",
	"Stay positive and believe in your abilities",
	"Stay motivated and set goals for yourself",
	"Stay resilient and learn from your mistakes",
	"Stay disciplined and prioritize your tasks",
	"Stay organized and manage your time effectively",
	"Stay focused and avoid procrastination",
	"Stay curious and explore new ideas",
	"Stay engaged and participate in class discussions",
	"Stay open-minded and consider different perspectives",
	"Stay patient and persevere through difficult tasks",
	"Stay positive and believe in yourself",
	"Stay motivated and set realistic goals",
	"Stay resilient and bounce back from setbacks",
	"Stay disciplined and follow through on your commitments",
	"Stay organized and keep track of your progress",
	"Stay focused and avoid distractions",
	"Stay curious and ask questions",
	"Stay engaged and participate actively in your learning",
	"Stay open-minded and consider different viewpoints",
	"Stay patient and persevere through challenges",
	"Stay positive and believe in your abilities",
	"Stay motivated and set goals for yourself",
	"Stay resilient and learn from your mistakes",
	"Stay disciplined and prioritize your tasks",
	"Stay organized and manage your time effectively",
	"Stay focused and avoid procrastination",
	"Stay curious and explore new ideas",
	"Stay engaged and participate in class discussions",
	"Stay open-minded and consider different perspectives",
	"Stay patient and persevere through difficult tasks",
	"Stay positive and believe in yourself",
	"Stay motivated and set realistic goals",
	"Stay resilient and bounce back from setbacks",
	"Stay disciplined and follow through on your commitments",
	"Stay organized and keep track of your progress",
	"Stay focused and avoid distractions",
	"Stay curious and ask questions",
	"Stay engaged and participate actively in your learning",
	"Stay open-minded and consider different viewpoints",
	"Stay patient and persevere through challenges",
	"Stay positive and believe in your abilities",
	"Stay motivated and set goals for yourself",
	"Stay resilient and learn from your mistakes",
	"Stay disciplined and prioritize your tasks",
	"Stay organized and manage your time effectively",
	"Stay focused and avoid procrastination",
	"Stay curious and explore new ideas",
	"Stay engaged and participate in class discussions",
];

export async function studyTips(interaction: any) {
	const randomTip = tips[Math.floor(Math.random() * studyTips.length)];
	const embed = new EmbedBuilder()
    .setTitle('💡 Study Tip')
    .setDescription(randomTip)
    .setColor('#90EE90')
    .setTimestamp();
	
	await interaction.reply({ 
		embeds: [embed],
		ephemeral: true 
	});
}